                                                                                                                                                                                                                                                                                                                                                                        import PaymentSuccessClient from "@/components/PaymentSuccessClient";
                                                                                                                                                                                                                                                                                                                                                                        import { checkPaymongoPaymentStatus } from "@/app/admin/transactions/actions";

                                                                                                                                                                                                                                                                                                                                                                        type SearchParams = { [key: string]: string | string[] | undefined };

                                                                                                                                                                                                                                                                                                                                                                        function extractIdFromUrl(url: string) {
                                                                                                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                                                                                            const m = url.match(/\/user\/services\/requests\/([^\/?#]+)/);
                                                                                                                                                                                                                                                                                                                                                                            if (m) return m[1];
                                                                                                                                                                                                                                                                                                                                                                          } catch {
                                                                                                                                                                                                                                                                                                                                                                            // ignore
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                          return null;
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        export default async function PaymentSuccessPage({ searchParams }: { searchParams?: SearchParams }) {
                                                                                                                                                                                                                                                                                                                                                                          // Try to find a transaction id from common query parameters or embedded URLs
                                                                                                                                                                                                                                                                                                                                                                          const params = searchParams || {};
                                                                                                                                                                                                                                                                                                                                                                          const candidates = [
                                                                                                                                                                                                                                                                                                                                                                            "transactionId",
                                                                                                                                                                                                                                                                                                                                                                            "transaction_id",
                                                                                                                                                                                                                                                                                                                                                                            "transaction",
                                                                                                                                                                                                                                                                                                                                                                            "id",
                                                                                                                                                                                                                                                                                                                                                                            "tx",
                                                                                                                                                                                                                                                                                                                                                                            "ref",
                                                                                                                                                                                                                                                                                                                                                                            "reference",
                                                                                                                                                                                                                                                                                                                                                                            "referenceId",
                                                                                                                                                                                                                                                                                                                                                                            "checkoutSessionId",
                                                                                                                                                                                                                                                                                                                                                                            "checkout_session",
                                                                                                                                                                                                                                                                                                                                                                            "session_id",
                                                                                                                                                                                                                                                                                                                                                                            "paymentId",
                                                                                                                                                                                                                                                                                                                                                                            "payment_id",
                                                                                                                                                                                                                                                                                                                                                                            "payment",
                                                                                                                                                                                                                                                                                                                                                                            "redirect",
                                                                                                                                                                                                                                                                                                                                                                          ];

                                                                                                                                                                                                                                                                                                                                                                          let transactionId: string | null = null;

                                                                                                                                                                                                                                                                                                                                                                          for (const k of candidates) {
                                                                                                                                                                                                                                                                                                                                                                            const raw = params[k] as string | undefined;
                                                                                                                                                                                                                                                                                                                                                                            if (!raw) continue;
                                                                                                                                                                                                                                                                                                                                                                            // if value looks like a URL path containing request id
                                                                                                                                                                                                                                                                                                                                                                            const fromUrl = extractIdFromUrl(raw);
                                                                                                                                                                                                                                                                                                                                                                            if (fromUrl) {
                                                                                                                                                                                                                                                                                                                                                                              transactionId = fromUrl;
                                                                                                                                                                                                                                                                                                                                                                              break;
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                            // otherwise take the value directly
                                                                                                                                                                                                                                                                                                                                                                            transactionId = raw;
                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                          let checkResult: any = null;
                                                                                                                                                                                                                                                                                                                                                                          if (transactionId) {
                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                              checkResult = await checkPaymongoPaymentStatus(transactionId);
                                                                                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                              console.error("Payment success status check failed:", err);
                                                                                                                                                                                                                                                                                                                                                                              checkResult = { success: false, error: "check failed" };
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                          const redirectUrl = transactionId ? `/user/services/requests/${transactionId}` : "/user/services/requests";

                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                            <PaymentSuccessClient redirectUrl={redirectUrl} status={checkResult?.status} />
                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                        }
